[workspace]
authors = ["{{ cookiecutter.author }} <{{ cookiecutter.author_email }}>"]
channels = ["conda-forge"]
name = "AD{{ cookiecutter.driver_name }}"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
lint = "pre-commit run --all-files"
build = "make -sj"
make-paramdefs = "dbtools-gen-paramdefs {{ cookiecutter.driver_name }}App/Db {{ cookiecutter.driver_name }}App/src"
make-bobfiles = "epicsdb2bob {{ cookiecutter.driver_name }}App/Db {{ cookiecutter.driver_name }}App/op/bob -d -r _RBV -t none"

[dependencies]
pre-commit = ">=4.3.0,<5"
ruff = ">=0.14.0,<0.15"
pip = ">=25.2,<26"
python = ">=3.12.12,<3.13"

[pypi-dependencies]
epicsdbtools = { git = "https://github.com/jwlodek/epicsdbtools.git" }
epicsdb2bob = { git = "https://github.com/NSLS2/epicsdb2bob.git" }
